In [ ]:
import pandas as pd

small = pd.read_json("small.json")
small

Задача: экспортировать JSON (small.json) в CSV и прочитать CSV как DataFrame.

In [3]:
import pandas as pd
import json
import os

json_path = "small.json"
csv_path = "small_export.csv"

with open(json_path, "r") as f:
    data = json.load(f)

df_json = pd.json_normalize(data, sep=".")
df_json.to_csv(csv_path)
df_json

,name,city,age,friends
0,Daniel,San Diego,48,"[{'name': 'Charlotte', 'hobbies': ['Quilting',..."
1,Sarah,Lahaina,39,"[{'name': 'Mia', 'hobbies': ['Church Activitie..."
2,Charlotte,Honolulu,49,"[{'name': 'Chris', 'hobbies': ['Socializing', ..."

In [4]:
import pandas as pd

small = pd.read_csv("small_export.csv")
small

,Unnamed: 0,name,city,age,friends
0,0,Daniel,San Diego,48,"[{'name': 'Charlotte', 'hobbies': ['Quilting',..."
1,1,Sarah,Lahaina,39,"[{'name': 'Mia', 'hobbies': ['Church Activitie..."
2,2,Charlotte,Honolulu,49,"[{'name': 'Chris', 'hobbies': ['Socializing', ..."

In [5]:
small.to_csv("test.csv")
a = pd.read_csv("test.csv")
a

,Unnamed: 0.1,Unnamed: 0,name,city,age,friends
0,0,0,Daniel,San Diego,48,"[{'name': 'Charlotte', 'hobbies': ['Quilting',..."
1,1,1,Sarah,Lahaina,39,"[{'name': 'Mia', 'hobbies': ['Church Activitie..."
2,2,2,Charlotte,Honolulu,49,"[{'name': 'Chris', 'hobbies': ['Socializing', ..."